name: "New Album"
description: "Suggest a new Album"
title: "[NEW] Album"
labels: ["enhancement"]
assignees:
  - T0biiii
body:
  - type: markdown
    attributes:
      value: "Suggest a new Artist for Songbattle.app"
  - type: input
    attributes:
      label: "Artist name?"
    validations:
      required: true
 - type: input
    attributes:
      label: "Album name?"
    validations:
      required: true
 - type: input
    attributes:
      label: "Linkt to Album"
    validations:
      required: false
