name: "New Album"
description: "Suggest a new Album"
title: "[NEW] Album"
labels: ["enhancement"]
assignees:
  - T0biiii
body:
  - type: markdown
    attributes:
      value: |
        Suggest a new Artist for Songbattle.app
  - type: textarea
    id: Artist
    attributes:
      label: "Artist name?"
      placeholder: "here goes the Artist name"
    validations:
      required: true
 - type: textarea
    id: Album
    attributes:
      label: "Album name?"
      placeholder: "here goes the Album name"
    validations:
      required: true
 - type: textarea
    id: Link
    attributes:
      label: "Linkt to Album"
      placeholder: "here goes the link to the Album"
    validations:
      required: false
